# Generated by Django 4.1.7 on 2023-03-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Местоположение"),
                ),
                ("lat", models.FloatField(unique=True, verbose_name="lat")),
                ("lng", models.FloatField(unique=True, verbose_name="lng")),
            ],
            options={
                "verbose_name": "Локация",
                "verbose_name_plural": "Локации",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Фамилия"
                    ),
                ),
                ("username", models.CharField(max_length=50, verbose_name="Никнейм")),
                ("password", models.CharField(max_length=150, verbose_name="password")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Администратор"),
                            ("moderator", "Модератор"),
                            ("member", "Участник"),
                        ],
                        default="member",
                        max_length=10,
                        verbose_name="Права пользователя",
                    ),
                ),
                ("age", models.IntegerField(verbose_name="Возраст")),
                (
                    "location",
                    models.ManyToManyField(
                        blank=True, to="users.location", verbose_name="Местоположение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
